services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: schedule-app
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: app_schedule
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
